# nothing kitty

font_family      JetBrains Mono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

background       #000000
foreground       #f5f5f5
cursor           #ff3122
cursor_text_color #000000
selection_background #141414
selection_foreground #f5f5f5

color0   #000000
color1   #ff3122
color2   #6fcf97
color3   #f5a623
color4   #3fa9f5
color5   #8b5cff
color6   #4dd0e1
color7   #f5f5f5
color8   #8a8a8a
color9   #ff3122
color10  #6fcf97
color11  #f5a623
color12  #3fa9f5
color13  #8b5cff
color14  #4dd0e1
color15  #ffffff

window_padding_width 12
window_border_width 1px
active_border_color  #ff3122
inactive_border_color #141414

enable_audio_bell no
confirm_os_window_close 0
shell zsh

tab_bar_style powerline
tab_powerline_style angled
tab_title_template "{index}"
active_tab_background #ff3122
active_tab_foreground #000000
inactive_tab_background #141414
inactive_tab_foreground #8a8a8a
