# autostart — one process per line, keep it boring

exec-once = waybar
exec-once = dunst
exec-once = swww-daemon
exec-once = ~/dotfiles/scripts/make-wallpaper.sh
exec-once = xdg-user-dirs-update
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store
